/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unir.view;

import java.awt.Dimension;
import javax.swing.*;
import org.unir.core.Order;
import org.unir.core.OrderCollection;

/**
 *
 * @author msanchcr
 */
public class DistributorView extends javax.swing.JFrame {

    private final String JFRAME_TITLE = "Distributor view";
    private final String JBUTTON_BACK = "Back";
    private final String JBUTTON_DELIVER = "Deliver";
    private final String JBUTTON_CANCEL = "Cancel";
    private final String JLABEL_ORDERS = "Pending orders";
    
    private static DistributorView instance;
    JList <Order> listOrders;
    /**
     * Creates new form DistributorView
     */
    public DistributorView() {
        initComponents();
        if (instance == null) {
            instance = this;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelForm = new javax.swing.JPanel();
        panelActionButtons = new javax.swing.JPanel();
        deliver = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        panelNav = new javax.swing.JPanel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(JFRAME_TITLE);
        setPreferredSize(new java.awt.Dimension(1000, 300));

        panelMain.setLayout(new javax.swing.BoxLayout(panelMain, javax.swing.BoxLayout.PAGE_AXIS));
        panelMain.add(panelForm);
        listOrders = new JList<Order>();
        listOrders.setPreferredSize(new Dimension(900, 500));
        panelForm.add(listOrders);
        listOrders.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        listOrders.setLayoutOrientation(JList.VERTICAL);
        listOrders.setVisibleRowCount(10);

        deliver.setText(JBUTTON_DELIVER);
        deliver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverActionPerformed(evt);
            }
        });
        panelActionButtons.add(deliver);

        cancel.setText(JBUTTON_CANCEL);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        panelActionButtons.add(cancel);

        panelMain.add(panelActionButtons);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        back.setText(JBUTTON_BACK);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        panelNav.add(back);

        getContentPane().add(panelNav, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        System.out.println("Back button has been clicked.");
        MainView mainView = MainView.getInstance();
        mainView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        System.out.println("Cancel button has been clicked.");
        Order order = listOrders.getSelectedValue();
        OrderCollection.getInstance();
        OrderCollection.getCollection().remove(order);
        System.out.println("Cancel button has been clicked.");
        System.out.println(String.format(
            "Order %s has been cancelled.",
            order
        ));
            this.loadData();
            this.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void deliverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverActionPerformed
        System.out.println("Deliver button has been clicked.");
        Order order = listOrders.getSelectedValue();
        OrderCollection.getInstance();
        OrderCollection.getCollection().remove(order);
        System.out.println("Deliver button has been clicked");
        System.out.println(String.format(
            "Order %s has been delivered.",
            order
        ));
        this.loadData();
        this.setVisible(true);
    }//GEN-LAST:event_deliverActionPerformed
    
    public static DistributorView getInstance () {
        if (instance == null ) {
            instance = new DistributorView();
        }
        return instance;
    }
    
    public void loadData() {
        OrderCollection.getInstance();
        DefaultListModel<Order> model = new DefaultListModel<Order>();
        for (Order order: OrderCollection.getCollection()) {
            model.add(
                OrderCollection.getCollection().indexOf(order),
                order
            );
        }
        this.listOrders.setModel(model);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton cancel;
    private javax.swing.JButton deliver;
    private javax.swing.JPanel panelActionButtons;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelNav;
    // End of variables declaration//GEN-END:variables
}
