/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unir.view;

/**
 *
 * @author msanchcr
 */
public class MainView extends javax.swing.JFrame {

    private final String JFRAME_TITLE = "Pharmacy App";
    private final String JBUTTON_PHARMACY = "Pharmacy";
    private final String JBUTTON_DELIVERY = "Delivery";
    
    private static MainView instance;
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        if (instance == null) {
            instance = this;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        pharmacyView = new javax.swing.JButton();
        distributorView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(JFRAME_TITLE);

        pharmacyView.setText(JBUTTON_PHARMACY);
        pharmacyView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pharmacyViewActionPerformed(evt);
            }
        });
        panelMain.add(pharmacyView);

        distributorView.setText(JBUTTON_DELIVERY);
        distributorView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distributorViewActionPerformed(evt);
            }
        });
        panelMain.add(distributorView);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pharmacyViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pharmacyViewActionPerformed
        // TODO add your handling code here:
        System.out.println("PharmacyView button has been clicked.");
        PharmacyView pharmacyView = PharmacyView.getInstance();
        pharmacyView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pharmacyViewActionPerformed

    private void distributorViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distributorViewActionPerformed
        System.out.println("Delivery button has been clicked.");
        DistributorView distributorView = DistributorView.getInstance();
        distributorView.loadData();
        distributorView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_distributorViewActionPerformed
    
    public static MainView getInstance() {
        if (instance == null) {
            instance = new MainView();
        }
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton distributorView;
    private javax.swing.JPanel panelMain;
    private javax.swing.JButton pharmacyView;
    // End of variables declaration//GEN-END:variables
}
