/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.unir.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JRadioButton;
import org.unir.core.DistributorEnum;
import org.unir.core.MedicineEnum;
import org.unir.core.Order;
import org.unir.core.OrderFactory;
import org.unir.util.Util;

/**
 *
 * @author msanchcr
 */
public class PharmacyView extends javax.swing.JFrame {

    private final String JFRAME_TITLE = "Pharmacy view";
    private final String JBUTTON_BACK = "Back";
    private final String JBUTTON_SUBMIT = "Submit";
    private final String JBUTTON_CLEAR = "Clear";
    private final String JLABEL_FIELD_NAME = "Name: ";
    private final String JLABEL_FIELD_TYPE = "Type: ";
    private final String JLABEL_FIELD_AMOUNT = "Amount: ";
    private final String JLABEL_FIELD_DISTRIBUTOR = "Distributor: ";
    private final String JLABEL_FIELD_DIRECTIONS = "Directions: ";
    private final String JLABEL_DIR_1 = "Calle de la Rosa 28";
    private final String JLABEL_DIR_2 = "Calle Alcazabilla 3";
    
    private static PharmacyView instance;
    /**
     * Creates new form PharmacyView
     */
    public PharmacyView() {
        initComponents();
        if (instance == null) {
            instance = this;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldDistributor = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        panelForm = new javax.swing.JPanel();
        panelFieldName = new javax.swing.JPanel();
        labelFieldName = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        panelFieldType = new javax.swing.JPanel();
        labelFieldType = new javax.swing.JLabel();
        fieldType = new javax.swing.JComboBox<>();
        panelFieldAmount = new javax.swing.JPanel();
        labelFieldAmount = new javax.swing.JLabel();
        textFieldAmount = new javax.swing.JTextField();
        panelFieldDistributor = new javax.swing.JPanel();
        labelFieldDistributor = new javax.swing.JLabel();
        panelDirections = new javax.swing.JPanel();
        labelFieldDirections = new javax.swing.JLabel();
        direction1 = new javax.swing.JCheckBox();
        direction2 = new javax.swing.JCheckBox();
        panelActionButtons = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        panelNav = new javax.swing.JPanel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(JFRAME_TITLE);

        panelMain.setLayout(new java.awt.BorderLayout());

        panelForm.setLayout(new javax.swing.BoxLayout(panelForm, javax.swing.BoxLayout.PAGE_AXIS));

        labelFieldName.setText(JLABEL_FIELD_NAME);
        panelFieldName.add(labelFieldName);

        textFieldName.setPreferredSize(new java.awt.Dimension(300, 20));
        panelFieldName.add(textFieldName);

        panelForm.add(panelFieldName);

        labelFieldType.setText(JLABEL_FIELD_TYPE);
        panelFieldType.add(labelFieldType);

        panelFieldType.add(fieldType);
        for (MedicineEnum medicine: MedicineEnum.values()) {
            fieldType.addItem(medicine.getMedicineName());
        }

        panelForm.add(panelFieldType);

        labelFieldAmount.setText(JLABEL_FIELD_AMOUNT);
        panelFieldAmount.add(labelFieldAmount);

        textFieldAmount.setPreferredSize(new java.awt.Dimension(100, 20));
        panelFieldAmount.add(textFieldAmount);

        panelForm.add(panelFieldAmount);

        labelFieldDistributor.setText(JLABEL_FIELD_DISTRIBUTOR);
        panelFieldDistributor.add(labelFieldDistributor);

        panelForm.add(panelFieldDistributor);

        labelFieldDirections.setText(JLABEL_FIELD_DIRECTIONS);
        panelDirections.add(labelFieldDirections);

        direction1.setText(JLABEL_DIR_1);
        panelDirections.add(direction1);

        direction2.setText(JLABEL_DIR_2);
        panelDirections.add(direction2);

        panelForm.add(panelDirections);

        submit.setText(JBUTTON_SUBMIT);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        panelActionButtons.add(submit);

        clear.setText(JBUTTON_CLEAR);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        panelActionButtons.add(clear);

        panelForm.add(panelActionButtons);
        for (DistributorEnum distributor: DistributorEnum.values()) {
            JRadioButton radioButton = new JRadioButton(distributor.getDistributorName());
            radioButton.setActionCommand(distributor.getDistributorName());
            fieldDistributor.add(radioButton);
            panelFieldDistributor.add(radioButton);
        }

        panelMain.add(panelForm, java.awt.BorderLayout.CENTER);

        back.setText(JBUTTON_BACK);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavLayout = new javax.swing.GroupLayout(panelNav);
        panelNav.setLayout(panelNavLayout);
        panelNavLayout.setHorizontalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNavLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(back)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panelNavLayout.setVerticalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelNavLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(back)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panelMain.add(panelNav, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panelMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        System.out.println("Back button has been clicked.");
        MainView mainView = MainView.getInstance();
        mainView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        System.out.println("Submit button has been clicked.");
        List<String> directions = new ArrayList<String> ();
        if (direction1.isSelected()) {
            directions.add(direction1.getText());
        }
        if (direction2.isSelected()) {
            directions.add(direction2.getText());
        }
        OrderFactory factory = OrderFactory.getInstance();
        try {
            Order order = factory.create(
                (textFieldName.getText() == null) ? null : textFieldName.getText(),
                (fieldType.getSelectedItem() == null)? null : fieldType.getSelectedItem().toString(),
                Util.parseInt(textFieldAmount.getText()),
                (fieldDistributor.getSelection() == null)? null : fieldDistributor.getSelection().getActionCommand(),
                directions
            );
            System.out.println("New order has been created:");
            System.out.println(order);
            this.clearActionPerformed(null);
        } catch (IllegalArgumentException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_submitActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        System.out.println("Clear button has been clicked.");
        textFieldName.setText(null);
        fieldType.setSelectedIndex(0);
        textFieldAmount.setText(null);
        fieldDistributor.clearSelection();
        direction1.setSelected(false);
        direction2.setSelected(false);
    }//GEN-LAST:event_clearActionPerformed
    
    public static PharmacyView getInstance() {
        if (instance == null) {
            instance = new PharmacyView();
        }
        return instance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JCheckBox direction1;
    private javax.swing.JCheckBox direction2;
    private javax.swing.ButtonGroup fieldDistributor;
    private javax.swing.JComboBox<String> fieldType;
    private javax.swing.JLabel labelFieldAmount;
    private javax.swing.JLabel labelFieldDirections;
    private javax.swing.JLabel labelFieldDistributor;
    private javax.swing.JLabel labelFieldName;
    private javax.swing.JLabel labelFieldType;
    private javax.swing.JPanel panelActionButtons;
    private javax.swing.JPanel panelDirections;
    private javax.swing.JPanel panelFieldAmount;
    private javax.swing.JPanel panelFieldDistributor;
    private javax.swing.JPanel panelFieldName;
    private javax.swing.JPanel panelFieldType;
    private javax.swing.JPanel panelForm;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelNav;
    private javax.swing.JButton submit;
    private javax.swing.JTextField textFieldAmount;
    private javax.swing.JTextField textFieldName;
    // End of variables declaration//GEN-END:variables
}
